// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: admin.sql

package db

import (
	"context"
	"database/sql"
)

const createAdmin = `-- name: CreateAdmin :execresult
INSERT INTO Admin (username, password) VALUES ("admin", "admin")
`

func (q *Queries) CreateAdmin(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAdmin)
}
