// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID          int32     `json:"id"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	Datecreated time.Time `json:"datecreated"`
	Dateupdate  time.Time `json:"dateupdate"`
}

type Tutor struct {
	ID          int32         `json:"id"`
	Fullname    string        `json:"fullname"`
	Gender      string        `json:"gender"`
	Email       string        `json:"email"`
	Phone       string        `json:"phone"`
	Validate    string        `json:"validate"`
	Adminid     sql.NullInt32 `json:"adminid"`
	Datecreated time.Time     `json:"datecreated"`
	Dateupdated sql.NullTime  `json:"dateupdated"`
}

type TutorPassword struct {
	ID       int32  `json:"id"`
	TutorID  int32  `json:"tutor_id"`
	Password string `json:"password"`
}

type User struct {
	ID          int32        `json:"id"`
	Fullname    string       `json:"fullname"`
	Gender      string       `json:"gender"`
	Email       string       `json:"email"`
	Phone       string       `json:"phone"`
	Blocked     bool         `json:"blocked"`
	Datecreated time.Time    `json:"datecreated"`
	Dateupdated sql.NullTime `json:"dateupdated"`
}

type UserPassword struct {
	ID       int32  `json:"id"`
	UserID   int32  `json:"user_id"`
	Password string `json:"password"`
}
