// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID          int32     `json:"id"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	Datecreated time.Time `json:"datecreated"`
	Dateupdate  time.Time `json:"dateupdate"`
}

type Tutor struct {
	ID          int32        `json:"id"`
	Fullname    string       `json:"fullname"`
	Gender      string       `json:"gender"`
	Age         int32        `json:"age"`
	Phone       string       `json:"phone"`
	Topic       string       `json:"topic"`
	Country     string       `json:"country"`
	City        string       `json:"city"`
	Datecreated time.Time    `json:"datecreated"`
	Dateupdated sql.NullTime `json:"dateupdated"`
}

type TutorPassword struct {
	ID       int32  `json:"id"`
	TutorID  int32  `json:"tutor_id"`
	Password string `json:"password"`
}

type User struct {
	ID          int32        `json:"id"`
	Fullname    string       `json:"fullname"`
	Gender      string       `json:"gender"`
	Phone       string       `json:"phone"`
	Datecreated time.Time    `json:"datecreated"`
	Dateupdated sql.NullTime `json:"dateupdated"`
}

type UserPassword struct {
	ID       int32  `json:"id"`
	UserID   int32  `json:"user_id"`
	Password string `json:"password"`
}
