// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAdmin(ctx context.Context) (sql.Result, error)
	CreateTutor(ctx context.Context, arg CreateTutorParams) (sql.Result, error)
	CreateTutorPassword(ctx context.Context, arg CreateTutorPasswordParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	CreateUserPassword(ctx context.Context, arg CreateUserPasswordParams) error
	DeleteTutor(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	DeleteUserPassword(ctx context.Context, userID int32) error
	GetTutor(ctx context.Context, id int32) (Tutor, error)
	GetTutorByPhone(ctx context.Context, phone string) (Tutor, error)
	GetTutorPassword(ctx context.Context, tutorID int32) (TutorPassword, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserPassword(ctx context.Context, userID int32) (UserPassword, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateTutorInfo(ctx context.Context, arg UpdateTutorInfoParams) (sql.Result, error)
	UpdateTutorPassword(ctx context.Context, arg UpdateTutorPasswordParams) error
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
