// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Course struct {
	ID          int32        `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Price       int32        `json:"price"`
	Datecreated time.Time    `json:"datecreated"`
	Dateupdated sql.NullTime `json:"dateupdated"`
}

type CourseTutor struct {
	ID       int32 `json:"id"`
	CourseID int32 `json:"course_id"`
	TutorID  int32 `json:"tutor_id"`
}

type CourseUser struct {
	ID       int32 `json:"id"`
	CourseID int32 `json:"course_id"`
	UserID   int32 `json:"user_id"`
}

type Feedback struct {
	ID          int32        `json:"id"`
	CourseID    int32        `json:"course_id"`
	UserID      int32        `json:"user_id"`
	Content     string       `json:"content"`
	Datecreated time.Time    `json:"datecreated"`
	Dateupdated sql.NullTime `json:"dateupdated"`
}

type Lecture struct {
	ID          int32        `json:"id"`
	CourseID    int32        `json:"course_id"`
	Title       string       `json:"title"`
	Content     string       `json:"content"`
	Datecreated time.Time    `json:"datecreated"`
	Dateupdated sql.NullTime `json:"dateupdated"`
}
